---

root: true

plugins:
  - prettier

env:
  browser: true
  es2020: true
  jest: true

extends:
  - 'airbnb-base'
  - 'prettier'
  - 'plugin:prettier/recommended'

rules:
  import/extensions: 0
  import/no-unresolved: 0
  no-param-reassign: 0
  import/no-extraneous-dependencies: [
    'error',
    {
      'devDependencies': [
        'postcss.config.js',
        'webpack.config.babel.js',
        'jest-setup.js',
        '__tests__/app.test.js'
      ]
    }
  ]
